### ISSUE TITLE
Help in Cordova

### ISSUE THREAD

**Issue by matamicen** [owntheweb/phonegap-ibeacon-test#3]
Hi Chris!
Thanks for your app!

I am installing for android and is not working to me.

May be I am doing something wrong, I am using Apache Cordova in Linux.

I saw in the Config.XML that you are uisng something like this:

 <gap:plugin name="org.apache.cordova.dialogs"/>

so I Added those plugins like this:

cordova plugin add org.apache.cordova.inappbrowser

then cordova's tell me that this plugin is old and suggest me to use another one, look at this:

WARNING: org.apache.cordova.inappbrowser has been renamed to cordova-plugin-inappbrowser. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.inappbrowser` and `cordova plugin add cordova-plugin-inappbrowser`.

I didn't remove the org.apache.cordova.inappbrowser I kept the old one installed.

I did the same with all the plugins you are using on the config.XML ...

The app. in android doesn't do anything to me, it keeps with the first screen andthe titles: iBeacons: Range/Proximity, Range Range Tag identifier RSS and State State Label identifier.

I changed the BeaconMonitor.Js and added my UUID in the string and Major minor (in decimal), then I put the Serial Number of my beacon on the IDENTIFIER, is that correct? I don't understand so much the identifier field.

so Can you help me ?

Thanks!

**Comment by owntheweb-archive** [comment]
I'm not sure how to assist at the moment if you are building this locally (I still need to climb the learning curve there). As this app was developed for use in Adobe PhoneGap Build (with possible changes in config.xml and directory structure in general), I recommend starting with fresh files and changing your iBeacon settings as you did, then run it through Adobe PhoneGap Build (the first project is free I think). 

Separate from that, what version of Android are you using? iBeacon support started at Android v4.3, and you'll need to check to see if your device has Bluetooth Low Energy (BLE) hardware available.

Sorry I couldn't help further right now, but do let me know how you made it work if you build it locally so that I can update my instructions (and try it out!). :D

**Comment by owntheweb-archive** [comment]
I'm going to close this support request as it has been inactive for some time. If you were able to get this going with your cordova setup, let me know how you did it. I'll update the instructions for everyone else. ;)
